name: Trigger Build LaTeX document

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call_build_latex:
    uses: cybersecurity-polito/latex-workflow/.github/workflows/build_latex_workflow.yml@main
    with:
      root_file: 'main.tex'
      prerelease: false
    secrets:
      envPAT: ${{ secrets.TOKEN }}