name: Trigger Build LaTeX document

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call_build_latex:
    uses: ./.github/workflows/build_latex_workflow.yml
    with:
      root_file: 'main.tex'
      prerelease: false